#!/bin/sh

# create pynsist_pkgs folder used in building windows installer
# This is based on the 2-extract.sh script from the pynsist pygi
# example (https://github.com/takluyver/pynsist)

# see create pynsist_pkgs script for instructions

if [ ! -e pygi.exe ]
then
    echo "pygi.exe not found"
    exit
fi

mkdir pynsist_pkgs

# Unzip the bindings
7za x pygi.exe -opygi

# Copy the PyGI packages into the pynsist_pkgs folder
7za x pygi/binding/py3.4-32/py3.4-32.7z -obindings
cp -r bindings/* pynsist_pkgs
rm -r bindings

# Copy the noarch and specified architecture dependencies into the gnome folder
array=( ATK Base GDK GDKPixbuf GTK HarfBuzz JPEG Pango WebP TIFF )

for i in "${array[@]}"
do
    echo -e "\nProcessing $i dependency"
    7za x pygi/noarch/$i/$i.data.7z -o$i-noarch
    cp -r $i-noarch/gnome/* pynsist_pkgs/gnome
    rm -r $i-noarch

    7za x pygi/rtvc10-32/$i/$i.bin.7z -o$i-arch
    cp -r $i-arch/gnome/* pynsist_pkgs/gnome
    rm -r $i-arch
done

#Remove pygi Folder
rm -r pygi

#Compile glib schemas
glib-compile-schemas pynsist_pkgs/gnome/share/glib-2.0/schemas/
